FROM ubuntu:22.04

RUN apt-get update -y \
    && apt-get install -y python3 \
        python3-pip \
        docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir
ADD Dockerfile Dockerfile
ADD build-image.py build-image.py
ADD requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "build-image.py"]
